/* 自動生成ファイル - 直接編集しないでください。movies.json から自動生成されます。 */
window.__MOVIES__ = {
  "updatedAt": "2026-09-09",
  "targetPeriod": "2026年9月上旬〜10月上旬",
  "nextUpdate": "2026-09-13",
  "isSampleData": false,
  "posterCredit": "ポスター画像・作品データの一部は TMDB のものを利用しています。This product uses the TMDB API but is not endorsed or certified by TMDB.",
  "criteria": {
    "audience": "大人／こども(小学生以下)の両方",
    "area": "横浜周辺のシネコンで観られるか",
    "period": "公開中の作品が中心（直近の公開予定も少し）",
    "count": "大人向け・こども向け 各8〜12本",
    "focus": "ムビチケ前売券の販売期間・入場者特典",
    "updateCycle": "2週間に1回（隔週日曜21時に自動更新）"
  },
  "movies": [
    {
      "title": "映画ちいかわ 人魚の島のひみつ",
      "audience": "both",
      "status": "now",
      "releaseDate": "2026-07-24",
      "releaseLabel": "2026年7月24日(金)公開",
      "rating": "",
      "runtime": 99,
      "genre": "アニメ",
      "dubbed": false,
      "synopsis": "ちいかわとハチワレのもとに、謎のうさぎから「特別な島へご招待」と書かれた招待状が届く。仲間たちと訪れた人魚の島で、新たな冒険とひみつが待ち受ける。",
      "posterUrl": "https://image.tmdb.org/t/p/w500/e8CPLRiIMes9RGxaW5GnGP2XPDg.jpg",
      "tmdbId": 1586876,
      "mubichike": {
        "available": false,
        "salesLabel": "",
        "types": "",
        "price": "",
        "note": "公開中のため前売券の販売は終了しています",
        "url": ""
      },
      "bonuses": [
        {
          "phase": "第4弾",
          "period": "9/5(土)〜",
          "content": "チャームミニフィギュア（島二郎・ヒトハ・フタバ・セイレーンの4種からランダム1点）",
          "limited": true,
          "note": ""
        }
      ],
      "bonusNote": "",
      "theaters": [],
      "officialUrl": "https://chiikawa-movie.jp/",
      "note": "興行ランキング上位の話題作",
      "needsCheck": false,
      "checkReason": ""
    },
    {
      "title": "べべフィン・ザ・ムービー うたとまほうのピンキッツワールド",
      "audience": "kids",
      "status": "now",
      "releaseDate": "2026-09-04",
      "releaseLabel": "2026年9月4日(金)公開",
      "rating": "",
      "runtime": null,
      "genre": "アニメ・ファミリー",
      "dubbed": true,
      "synopsis": "赤ちゃんのフィン、お姉ちゃんのボラー、お兄ちゃんのブロディの3きょうだい。魔法のタブレットの光に吸い込まれたフィンを追い、ボラーとブロディは魔法使いのピンキッツとともにピンキッツワールドへ冒険に出る。",
      "posterUrl": "",
      "tmdbId": null,
      "mubichike": {
        "available": false,
        "salesLabel": "",
        "types": "",
        "price": "",
        "note": "公開中のため前売券の販売は終了しています",
        "url": ""
      },
      "bonuses": [
        {
          "phase": "",
          "period": "9/4(金)〜",
          "content": "ピンキッツ バルーン人形",
          "limited": true,
          "note": "配布対象は小学生以下のみ"
        }
      ],
      "bonusNote": "",
      "theaters": [],
      "officialUrl": "https://www.pinkfong.com/bebefinn-the-movie/",
      "note": "未就学児向け",
      "needsCheck": false,
      "checkReason": ""
    },
    {
      "title": "THE RIBBON HERO リボンヒーロー",
      "audience": "both",
      "status": "now",
      "releaseDate": "2026-09-04",
      "releaseLabel": "2026年9月4日(金)公開（劇場2週間限定）",
      "rating": "",
      "runtime": 108,
      "genre": "アニメ",
      "dubbed": false,
      "synopsis": "かつて怪物ネルガルに故郷を奪われた亡国の王女サファイア。絶望を乗り越え希望の騎士となった彼女は、新たに見つけた居場所を破滅の運命から救うため、再び剣を手に立ち上がる。",
      "posterUrl": "https://image.tmdb.org/t/p/w500/79APJkTug1OzTrTtTmSmy2TgSuU.jpg",
      "tmdbId": 1679730,
      "mubichike": {
        "available": false,
        "salesLabel": "",
        "types": "",
        "price": "",
        "note": "公開中のため前売券の販売は終了しています",
        "url": ""
      },
      "bonuses": [
        {
          "phase": "1週目",
          "period": "9/4(金)〜9/10(木)",
          "content": "主題歌『Reborn』収録CD",
          "limited": true,
          "note": "配布は9/10(木)までの予定です"
        }
      ],
      "bonusNote": "",
      "theaters": [],
      "officialUrl": "https://www.theribbonhero.com/",
      "note": "手塚治虫「リボンの騎士」原作。劇場公開は2週間限定（Netflixでも配信中）",
      "needsCheck": false,
      "checkReason": ""
    },
    {
      "title": "ミニオンズ＆モンスターズ",
      "audience": "both",
      "status": "now",
      "releaseDate": "2026-08-07",
      "releaseLabel": "2026年8月7日(金)公開",
      "rating": "",
      "runtime": 91,
      "genre": "アニメ・ファミリー",
      "dubbed": true,
      "synopsis": "最強最悪のボスを求めて旅するミニオンズがたどり着いたのは夢あふれるハリウッド。自分たちでモンスター映画を作ろうとして本物のモンスターを召喚してしまい、街は大パニックに。",
      "posterUrl": "https://image.tmdb.org/t/p/w500/8wYHlLEIrEKvbfj83B11g7FKFd8.jpg",
      "tmdbId": 1315772,
      "mubichike": {
        "available": false,
        "salesLabel": "",
        "types": "",
        "price": "",
        "note": "公開中のため前売券の販売は終了しています",
        "url": ""
      },
      "bonuses": [],
      "bonusNote": "現時点では確認できていません",
      "theaters": ["T・ジョイ横浜"],
      "officialUrl": "",
      "note": "",
      "needsCheck": false,
      "checkReason": ""
    },
    {
      "title": "映画クレヨンしんちゃん 奇々怪々！オラの妖怪バケ～ション",
      "audience": "kids",
      "status": "now",
      "releaseDate": "2026-07-31",
      "releaseLabel": "2026年7月31日(金)公開",
      "rating": "",
      "runtime": 101,
      "genre": "アニメ",
      "dubbed": false,
      "synopsis": "テレビアニメ「クレヨンしんちゃん」劇場版第33作。妖怪の国に迷い込んでしまった野原家が、どこか懐かしくも奇々怪々な世界で繰り広げる大冒険を描く。",
      "posterUrl": "https://image.tmdb.org/t/p/w500/15iwqqJVgFfeFh4Y1f8gg9yi2Fw.jpg",
      "tmdbId": 1598766,
      "mubichike": {
        "available": false,
        "salesLabel": "",
        "types": "",
        "price": "",
        "note": "公開中のため前売券の販売は終了しています",
        "url": ""
      },
      "bonuses": [],
      "bonusNote": "現時点では確認できていません（公開から1か月以上経過しており終了している可能性があります）",
      "theaters": [],
      "officialUrl": "https://shin-ei-animation.jp/works/movie_shinchan_2026/",
      "note": "公開から1か月以上経過しており、横浜周辺での上映が終了している可能性があります",
      "needsCheck": true,
      "checkReason": "公開から1か月以上経過しています。現在も上映しているか、劇場の上映スケジュールで確認してください"
    },
    {
      "title": "スパイダーマン：ブランド・ニュー・デイ",
      "audience": "both",
      "status": "now",
      "releaseDate": "2026-07-31",
      "releaseLabel": "2026年7月31日(金)公開",
      "rating": "",
      "runtime": 145,
      "genre": "洋画・アクション",
      "dubbed": true,
      "synopsis": "愛する人たちを守るため彼らの記憶から自らの存在を消したピーター・パーカーは、スパイダーマンとしてニューヨークの人々を守り続けている。そんな中、彼の体に驚くべき変異が起こり始める。",
      "posterUrl": "https://image.tmdb.org/t/p/w500/hvbs76wGMZYqJSvaRps5jDzHUhN.jpg",
      "tmdbId": 969681,
      "mubichike": {
        "available": false,
        "salesLabel": "",
        "types": "",
        "price": "",
        "note": "公開中のため前売券の販売は終了しています",
        "url": ""
      },
      "bonuses": [],
      "bonusNote": "現時点では確認できていません",
      "theaters": ["横浜ブルク13", "TOHOシネマズ ららぽーと横浜"],
      "officialUrl": "https://spiderman-movie.jp/",
      "note": "全米・国内ともにランキング上位。横浜ブルク13ではSCREENX上映も実施",
      "needsCheck": false,
      "checkReason": ""
    },
    {
      "title": "映画「宇宙なんちゃら こてつくん」うっかり出てきた宇宙人を探せ！",
      "audience": "kids",
      "status": "soon",
      "releaseDate": "2026-09-11",
      "releaseLabel": "2026年9月11日(金)公開",
      "rating": "",
      "runtime": 50,
      "genre": "アニメ・ファミリー",
      "dubbed": false,
      "synopsis": "宇宙アカデミーのパイロット科1年生・こてつが、学園の仲間たちと一緒に宇宙人探しに乗り出す。テレビアニメの再編集映像とJAXAの実際の宇宙探査映像を組み合わせた作品。",
      "posterUrl": "",
      "tmdbId": null,
      "mubichike": {
        "available": true,
        "salesLabel": "〜2026年9月10日(木)23:59（公開前日まで）",
        "types": "ムビチケカード / 前売オンライン券",
        "price": "",
        "note": "販売開始日・価格は確認できていません",
        "url": "https://ticket.moviewalker.jp/film/093466"
      },
      "bonuses": [
        {
          "phase": "",
          "period": "9/11(金)〜",
          "content": "映画オリジナル『宇宙なんちゃらマシュマロシール』",
          "limited": true,
          "note": "先着順での配布です"
        }
      ],
      "bonusNote": "",
      "theaters": [],
      "officialUrl": "https://space--academy.com/eiga.html",
      "note": "未就学児〜小学生向け。上映時間が短めの作品",
      "needsCheck": false,
      "checkReason": ""
    },
    {
      "title": "映画名探偵プリキュア！不思議な庭と2人の秘密",
      "audience": "kids",
      "status": "soon",
      "releaseDate": "2026-09-18",
      "releaseLabel": "2026年9月18日(金)公開",
      "rating": "",
      "runtime": null,
      "genre": "アニメ・ファミリー",
      "dubbed": false,
      "synopsis": "誕生日に妖精ポチタンと出会った明智あんなは、謎の光に飲み込まれてタイムスリップ。探偵志望の小林みくると出会い、名探偵プリキュアに変身して怪盗団ファントムに挑む、謎解きアドベンチャー。",
      "posterUrl": "https://image.tmdb.org/t/p/w500/bJg5Eh20xrIQIBgwCKJWLbajCsL.jpg",
      "tmdbId": 1663937,
      "mubichike": {
        "available": true,
        "salesLabel": "2026年6月26日(金)10:00〜9月17日(木)23:59（公開前日まで）",
        "types": "ムビチケカード（5種のビジュアルから選択） / 前売オンライン券",
        "price": "一般1,600円 / 小人（3歳以上）900円",
        "note": "劇場限定のプレゼント付きムビチケあり",
        "url": "https://ticket.moviewalker.jp/film/092834"
      },
      "bonuses": [
        {
          "phase": "",
          "period": "9/18(金)〜",
          "content": "ポチタンミラクルライト",
          "limited": true,
          "note": "配布対象は中学生以下のみ"
        }
      ],
      "bonusNote": "",
      "theaters": ["イオンシネマ みなとみらい"],
      "officialUrl": "https://www.precure-movie.com/",
      "note": "ミラクルライトは上映中に振って応援できる、こども向けの定番特典",
      "needsCheck": false,
      "checkReason": ""
    },
    {
      "title": "アベンジャーズ／エンドゲーム：アンコール",
      "audience": "both",
      "status": "soon",
      "releaseDate": "2026-09-23",
      "releaseLabel": "2026年9月23日(水・祝)〜10月8日(木) 期間限定公開",
      "rating": "",
      "runtime": null,
      "genre": "洋画・アクション",
      "dubbed": true,
      "synopsis": "サノスによって人類の半分が消滅した世界で、残されたアベンジャーズが最後の逆襲に挑む。12月公開の最新作『アベンジャーズ／ドゥームズデイ』への布石となる新規映像を追加した特別版。",
      "posterUrl": "https://image.tmdb.org/t/p/w500/uNWEDJzeH8VLHrs2iHkosYp2Y6W.jpg",
      "tmdbId": 299534,
      "mubichike": {
        "available": false,
        "salesLabel": "",
        "types": "",
        "price": "",
        "note": "2026年9月23日(水)〜10月8日(木)の期間限定上映（全国329館）。新規映像が追加されるため上映時間は未発表",
        "url": ""
      },
      "bonuses": [],
      "bonusNote": "現時点では確認できていません",
      "theaters": [],
      "officialUrl": "https://marvel.disney.co.jp/movie/avengers-doomsday/endgame-encore",
      "note": "全国329館で期間限定上映。新規映像追加による上映時間の変更有無は未確認",
      "needsCheck": false,
      "checkReason": ""
    },
    {
      "title": "白鳥とコウモリ",
      "audience": "adult",
      "status": "now",
      "releaseDate": "2026-09-04",
      "releaseLabel": "2026年9月4日(金)公開",
      "rating": "",
      "runtime": 145,
      "genre": "邦画・ミステリー",
      "dubbed": false,
      "synopsis": "善良な弁護士が刺殺された事件は、容疑者の自供により解決したはずだった。しかし容疑者の息子と被害者の娘は事件に違和感を抱き、出会うはずのない2人が真実を追い始める。東野圭吾原作。",
      "posterUrl": "https://image.tmdb.org/t/p/w500/jIEyBR9gCrDMEQ7UcxWmJVj2zDi.jpg",
      "tmdbId": 1621964,
      "mubichike": {
        "available": false,
        "salesLabel": "",
        "types": "",
        "price": "",
        "note": "7月17日(金)から販売されていましたが、公開中のため終了しています",
        "url": ""
      },
      "bonuses": [],
      "bonusNote": "現時点では確認できていません",
      "theaters": ["横浜ブルク13", "T・ジョイ横浜"],
      "officialUrl": "https://www.shochiku.co.jp/cinema/lineup/hakuchotokomori/",
      "note": "国内ランキング上位",
      "needsCheck": false,
      "checkReason": ""
    },
    {
      "title": "バックルームズ",
      "audience": "adult",
      "status": "now",
      "releaseDate": "2026-09-04",
      "releaseLabel": "2026年9月4日(金)公開",
      "rating": "",
      "runtime": 127,
      "genre": "洋画・ホラー",
      "dubbed": true,
      "synopsis": "家具店を経営するクラークは、店の地下から現実には存在しない奇妙な空間へ迷い込む。黄色い壁紙と蛍光灯に照らされた終わりのない部屋と廊下が続く不可思議な世界の謎に挑む、都市伝説発の恐怖体験。",
      "posterUrl": "https://image.tmdb.org/t/p/w500/z52Eabu4xm5I8ksqdKOSylo5wWL.jpg",
      "tmdbId": 1083381,
      "mubichike": {
        "available": false,
        "salesLabel": "",
        "types": "",
        "price": "",
        "note": "公開中のため前売券の販売は終了しています",
        "url": ""
      },
      "bonuses": [
        {
          "phase": "第1弾",
          "period": "9/4(金)〜",
          "content": "『バックルームズ』をもっと楽しむ小冊子",
          "limited": true,
          "note": ""
        }
      ],
      "bonusNote": "",
      "theaters": ["横浜ブルク13", "T・ジョイ横浜", "TOHOシネマズ 上大岡"],
      "officialUrl": "https://a24jp.com/films/backrooms/",
      "note": "全米初登場1位、世界44か国で初登場1位を記録したA24配給のヒットホラー",
      "needsCheck": false,
      "checkReason": ""
    },
    {
      "title": "劇場版 魔法少女まどか☆マギカ ワルプルギスの廻天",
      "audience": "adult",
      "status": "now",
      "releaseDate": "2026-08-28",
      "releaseLabel": "2026年8月28日(金)公開",
      "rating": "",
      "runtime": 119,
      "genre": "アニメ",
      "dubbed": false,
      "synopsis": "『叛逆の物語』の事件を経て、世界は表向き均衡を取り戻したかに見えた。しかしその平和はあまりにも脆く、ワルプルギスの夜に関連する新たな脅威が現れる。",
      "posterUrl": "https://image.tmdb.org/t/p/w500/tc7wW6whJSvxM9f5RdqmQVpdl6n.jpg",
      "tmdbId": 822653,
      "mubichike": {
        "available": false,
        "salesLabel": "",
        "types": "",
        "price": "",
        "note": "公開中のため前売券の販売は終了しています",
        "url": ""
      },
      "bonuses": [
        {
          "phase": "2週目",
          "period": "9/5(土)〜9/11(金)",
          "content": "蒼樹うめ 描きおろしミニ色紙風カード［第2弾］（全3種ランダム）",
          "limited": true,
          "note": ""
        }
      ],
      "bonusNote": "",
      "theaters": [],
      "officialUrl": "https://www.madoka-magica.com/wr/",
      "note": "アニメだが内容は大人向け。小学生以下には不向き",
      "needsCheck": false,
      "checkReason": ""
    },
    {
      "title": "SEKIRO: NO DEFEAT",
      "audience": "adult",
      "status": "now",
      "releaseDate": "2026-09-04",
      "releaseLabel": "2026年9月4日(金)公開（3週間限定上映）",
      "rating": "",
      "runtime": 107,
      "genre": "アニメ",
      "dubbed": false,
      "synopsis": "戦国時代を舞台に、剣聖・葦名一心が建立した葦名の国が存亡の危機に直面。その孫・弦一郎が竜胤の御子・九郎を求める中、隻腕の忍が戦いに身を投じる。ゲーム『SEKIRO』のアニメ映画化。",
      "posterUrl": "https://image.tmdb.org/t/p/w500/lBWZojUmupfmx3pqVZJIL2v7gF4.jpg",
      "tmdbId": 1725074,
      "mubichike": {
        "available": false,
        "salesLabel": "",
        "types": "",
        "price": "",
        "note": "公開中のため前売券の販売は終了しています",
        "url": ""
      },
      "bonuses": [
        {
          "phase": "1週目",
          "period": "9/4(金)〜9/11(金)",
          "content": "キャラクターデザイン・岸田隆宏 描きおろしビジュアルボード(B5)",
          "limited": true,
          "note": ""
        }
      ],
      "bonusNote": "",
      "theaters": ["T・ジョイ横浜", "横浜ブルク13"],
      "officialUrl": "https://sekiro-anime.jp/",
      "note": "3週間限定上映",
      "needsCheck": false,
      "checkReason": ""
    },
    {
      "title": "時には懺悔を",
      "audience": "adult",
      "status": "now",
      "releaseDate": "2026-08-28",
      "releaseLabel": "2026年8月28日(金)公開",
      "rating": "",
      "runtime": 129,
      "genre": "ドラマ",
      "dubbed": false,
      "synopsis": "内海文三の原作をもとに、刑事とその相棒が殺人事件の真相を追う中、過去に傷を抱えた大人たちが小さな命との出会いを通して再生していく姿を描く。構想18年、中島哲也監督の最新作。",
      "posterUrl": "https://image.tmdb.org/t/p/w500/l6HnJ4ZVK2oT20MaYTznAU1dkMH.jpg",
      "tmdbId": 1410587,
      "mubichike": {
        "available": false,
        "salesLabel": "",
        "types": "",
        "price": "",
        "note": "公開中のため前売券の販売は終了しています",
        "url": ""
      },
      "bonuses": [],
      "bonusNote": "現時点では確認できていません",
      "theaters": [],
      "officialUrl": "https://www.tokizan.jp/",
      "note": "レビュー評価の高い作品。中島哲也監督",
      "needsCheck": false,
      "checkReason": ""
    },
    {
      "title": "スワロウテイル（4Kリマスター）",
      "audience": "adult",
      "status": "now",
      "releaseDate": "2026-09-04",
      "releaseLabel": "2026年9月4日(金)公開（公開30周年記念・4Kリマスター版）",
      "rating": "",
      "runtime": 149,
      "genre": "邦画・ドラマ",
      "dubbed": false,
      "synopsis": "紙幣偽造のデータを手に入れた娼婦のグリコは、中国系移民のヒョウたちと偽札作りを始める。ライブハウスを買い取り歌手として有名になっていく彼女を軸に、近未来の無国籍都市\"円都\"を生きる若者たちを描く。",
      "posterUrl": "https://image.tmdb.org/t/p/w500/p67xuAENDxee2DZZfRQFiVH3iBR.jpg",
      "tmdbId": 8426,
      "mubichike": {
        "available": false,
        "salesLabel": "",
        "types": "",
        "price": "",
        "note": "リバイバル上映のため前売券の設定は確認できていません",
        "url": ""
      },
      "bonuses": [],
      "bonusNote": "現時点では確認できていません",
      "theaters": [],
      "officialUrl": "https://swallowtail4k.jp/",
      "note": "岩井俊二監督完全監修による公開30周年記念4Kリマスター＆Dolby Atmos版",
      "needsCheck": false,
      "checkReason": ""
    },
    {
      "title": "オデュッセイア",
      "audience": "adult",
      "status": "soon",
      "releaseDate": "2026-09-11",
      "releaseLabel": "2026年9月11日(金)公開",
      "rating": "",
      "runtime": 172,
      "genre": "洋画・ドラマ",
      "dubbed": false,
      "synopsis": "トロイア戦争の終結後、イタケーの伝説的な王オデュッセウスは、故郷への長く危険に満ちた帰還の旅に出る。神々の気まぐれや神話の怪物たちが、彼の知略と人間性を試す。クリストファー・ノーラン監督最新作。",
      "posterUrl": "https://image.tmdb.org/t/p/w500/oe40oI7aulGLkoNDEZWxyeIQGZq.jpg",
      "tmdbId": 1368337,
      "mubichike": {
        "available": true,
        "salesLabel": "2026年6月12日10:00〜9月10日(木)23:59（公開前日まで）",
        "types": "ムビチケカード / ムビチケオンライン券",
        "price": "1,600円",
        "note": "現時点で入場者特典の情報はありません",
        "url": "https://ticket.moviewalker.jp/film/090314"
      },
      "bonuses": [],
      "bonusNote": "入場者特典は現時点では確認できていません",
      "theaters": ["TOHOシネマズ ららぽーと横浜"],
      "officialUrl": "https://odyssey-film.jp/",
      "note": "全米ランキング上位",
      "needsCheck": false,
      "checkReason": ""
    },
    {
      "title": "最終楽章 響け！ユーフォニアム 後編",
      "audience": "adult",
      "status": "soon",
      "releaseDate": "2026-09-11",
      "releaseLabel": "2026年9月11日(金)公開",
      "rating": "",
      "runtime": 127,
      "genre": "アニメ",
      "dubbed": false,
      "synopsis": "難関の関西大会を突破し、全国大会出場に沸き立つ北宇治高校吹奏楽部。全国大会出場をかけたオーディションに向け、部員たちの葛藤と決意を描くシリーズ最終章の後編。",
      "posterUrl": "https://image.tmdb.org/t/p/w500/3nVufzgnnT9it02P7fa6KAxyKLu.jpg",
      "tmdbId": 1494419,
      "mubichike": {
        "available": false,
        "salesLabel": "",
        "types": "",
        "price": "",
        "note": "クリアファイル付きムビチケカードは完売、前売オンライン券も販売終了しており入手が難しい状況です",
        "url": ""
      },
      "bonuses": [
        {
          "phase": "",
          "period": "9/11(金)〜",
          "content": "「ゴールド箔押し！グラデュエ」",
          "limited": true,
          "note": ""
        }
      ],
      "bonusNote": "",
      "theaters": [],
      "officialUrl": "https://anime-eupho.com/",
      "note": "前編を観ていることが前提のシリーズ作品",
      "needsCheck": false,
      "checkReason": ""
    },
    {
      "title": "踊る大捜査線 N.E.W. メトロポリスを駆け抜けろ！",
      "audience": "adult",
      "status": "soon",
      "releaseDate": "2026-09-18",
      "releaseLabel": "2026年9月18日(金)公開",
      "rating": "",
      "runtime": 142,
      "genre": "邦画・アクション",
      "dubbed": false,
      "synopsis": "東京都内で誘拐事件が発生。犯人は身代金を指定場所まで持ってくるよう指示し、間に合わなければ街を爆破すると予告する。3Dプリンター拳銃による連続殺人事件も発生する中、青島は仲間と事件解決に奔走する。",
      "posterUrl": "https://image.tmdb.org/t/p/w500/zxpus1lIDG7wqAuzsD0zgM6mXwM.jpg",
      "tmdbId": 1491083,
      "mubichike": {
        "available": true,
        "salesLabel": "2026年7月17日(金)〜9月17日(木)（公開前日まで）",
        "types": "ムビチケカード（劇場・通販） / 前売オンライン券",
        "price": "1,500円（税込）",
        "note": "劇場でカードを買うとオリジナル N.E.W.ステッカーがもらえます（数量限定）。セブンネット／TOHO theater STORE／アニメイト限定のグッズ付き前売券もあり",
        "url": "https://ticket.moviewalker.jp/film/088341"
      },
      "bonuses": [],
      "bonusNote": "劇場公開時の入場者特典は現時点では確認できていません（前売券購入特典は上記の通り）",
      "theaters": ["横浜ブルク13", "T・ジョイ横浜", "TOHOシネマズ 上大岡"],
      "officialUrl": "https://odoru.com/odorunew/tickets.html",
      "note": "主題歌は織田裕二「Love Somebody」",
      "needsCheck": false,
      "checkReason": ""
    },
    {
      "title": "八つ墓村",
      "audience": "adult",
      "status": "soon",
      "releaseDate": "2026-09-18",
      "releaseLabel": "2026年9月18日(金)公開",
      "rating": "",
      "runtime": 117,
      "genre": "邦画・ミステリー",
      "dubbed": false,
      "synopsis": "大学生・井川辰弥のもとに舞い込んだ母の訃報。奇妙な探偵・金田一耕助に誘われ、岡山県山奥に潜む「八つ墓村」を訪れる。清水崇監督×尾上松也主演による横溝正史原作の完全新作映画化。",
      "posterUrl": "https://image.tmdb.org/t/p/w500/3xLSVAQZAs1DEUNm1TKYzx0kiLT.jpg",
      "tmdbId": 1716622,
      "mubichike": {
        "available": true,
        "salesLabel": "2026年7月3日10:00〜9月17日(木)23:59（公開前日まで）",
        "types": "ムビチケカード / 前売オンライン券",
        "price": "1,600円（税込）",
        "note": "オンライン券購入特典としてオリジナルスマホ壁紙あり",
        "url": "https://ticket.moviewalker.jp/film/092338"
      },
      "bonuses": [],
      "bonusNote": "劇場入場者特典は現時点では確認できていません",
      "theaters": [],
      "officialUrl": "https://www.shochiku.co.jp/cinema/lineup/yatsuhakamura/",
      "note": "清水崇監督×尾上松也の新解釈による『八つ墓村』",
      "needsCheck": false,
      "checkReason": ""
    },
    {
      "title": "ひゃくえむ。1周年記念リバイバル上映",
      "audience": "adult",
      "status": "soon",
      "releaseDate": "2026-09-18",
      "releaseLabel": "2026年9月18日(金)〜 1周年記念リバイバル上映（全国6劇場）",
      "rating": "",
      "runtime": null,
      "genre": "アニメ",
      "dubbed": false,
      "synopsis": "生まれつき足が速いトガシと、辛い現実を忘れるため走っていた転校生・小宮。100m走を通してライバルであり親友でもある関係になっていく2人を描く、ロトスコープ技法によるスポーツアニメ。",
      "posterUrl": "https://image.tmdb.org/t/p/w500/ftUHKZfXONnjuOGGpNeFCeAXbYF.jpg",
      "tmdbId": 1295026,
      "mubichike": {
        "available": false,
        "salesLabel": "",
        "types": "",
        "price": "",
        "note": "リバイバル上映のため前売券の設定は確認できていません",
        "url": ""
      },
      "bonuses": [
        {
          "phase": "",
          "period": "9/18(金)〜",
          "content": "キャラクターデザイン：小嶋慶祐 描き下ろし特製ポストカード（1周年ver.）",
          "limited": true,
          "note": ""
        }
      ],
      "bonusNote": "",
      "theaters": ["kino cinéma 横浜みなとみらい"],
      "officialUrl": "https://hyakuemu-anime.com/",
      "note": "日本アカデミー賞優秀アニメーション作品賞受賞作。全国6劇場（kino cinéma新宿／立川高島屋S.C.館／横浜みなとみらい、伏見ミリオン座、kino cinéma心斎橋／天神）での限定リバイバル上映",
      "needsCheck": false,
      "checkReason": ""
    },
    {
      "title": "劇場版 RE:cycle of the PENGUINDRUM 前編 君の列車は生存戦略",
      "audience": "adult",
      "status": "soon",
      "releaseDate": "2026-09-25",
      "releaseLabel": "2026年9月25日(金)〜10月1日(木) 1週間限定リバイバル上映",
      "rating": "",
      "runtime": 125,
      "genre": "アニメ",
      "dubbed": false,
      "synopsis": "妹の命を救うため、双子の兄弟は謎のペンギン帽の指示で「ピングドラム」を探すことになる。『輪るピングドラム』15周年を記念した1週間限定リバイバル上映。",
      "posterUrl": "https://image.tmdb.org/t/p/w500/g4JOzZ47Uncu6jJtmY4QWXSHGT4.jpg",
      "tmdbId": 813707,
      "mubichike": {
        "available": false,
        "salesLabel": "",
        "types": "",
        "price": "",
        "note": "15周年記念リバイバル上映のため前売券の設定は確認できていません",
        "url": ""
      },
      "bonuses": [
        {
          "phase": "",
          "period": "9/25(金)〜",
          "content": "ポスタービジュアルを使用したスマホサイズステッカー",
          "limited": false,
          "note": ""
        }
      ],
      "bonusNote": "",
      "theaters": ["横浜ブルク13"],
      "officialUrl": "https://penguindrum.jp/event/20260925.html",
      "note": "後編は10月2日(金)〜10月8日(木)に上映予定（後編にも同様のステッカー特典あり）。9/27には幾原邦彦監督・木村昴さん登壇のトークショー付き上映会も開催",
      "needsCheck": false,
      "checkReason": ""
    }
  ]
}
;
