/* 自動生成ファイル - 直接編集しないでください。movies.json から自動生成されます。 */
window.__MOVIES__ = {
  "updatedAt": "2026-09-27",
  "targetPeriod": "2026年9月下旬〜10月下旬",
  "nextUpdate": "2026-10-11",
  "isSampleData": false,
  "posterCredit": "ポスター画像・作品データの一部は TMDB のものを利用しています。This product uses the TMDB API but is not endorsed or certified by TMDB.",
  "criteria": {
    "audience": "大人／こども(小学生以下)の両方",
    "area": "横浜周辺のシネコンで観られるか",
    "period": "公開中の作品が中心（直近の公開予定も少し）",
    "count": "大人向け・こども向け 各8〜12本",
    "focus": "ムビチケ前売券の販売期間・入場者特典",
    "updateCycle": "2週間に1回（隔週日曜21時に自動更新）"
  },
  "movies": [
    {
      "title": "映画ちいかわ 人魚の島のひみつ",
      "audience": "both",
      "status": "now",
      "releaseDate": "2026-07-24",
      "releaseLabel": "2026年7月24日(金)公開",
      "rating": "",
      "runtime": 99,
      "genre": "アニメ",
      "dubbed": false,
      "synopsis": "ちいかわとハチワレのもとに、謎のうさぎから「特別な島へご招待」と書かれた招待状が届く。仲間たちと訪れた人魚の島で、新たな冒険とひみつが待ち受ける。",
      "posterUrl": "https://image.tmdb.org/t/p/w500/e8CPLRiIMes9RGxaW5GnGP2XPDg.jpg",
      "tmdbId": 1586876,
      "mubichike": {
        "available": false,
        "salesLabel": "",
        "types": "",
        "price": "",
        "note": "公開中のため前売券の販売は終了しています",
        "url": ""
      },
      "bonuses": [
        {
          "phase": "第5弾",
          "period": "9/19(土)〜",
          "content": "全52ページの「ひみつ本」（描き下ろし漫画・エッセイ、セイレーン編構想時のストーリーイラストなど収録）",
          "limited": true,
          "note": "劇場ごとに数量限定、なくなり次第配布終了"
        }
      ],
      "bonusNote": "",
      "theaters": ["横浜ブルク13", "T・ジョイ横浜", "イオンシネマ みなとみらい"],
      "officialUrl": "https://chiikawa-movie.jp/",
      "note": "興行ランキング上位の話題作",
      "needsCheck": false,
      "checkReason": ""
    },
    {
      "title": "ミニオンズ＆モンスターズ",
      "audience": "both",
      "status": "now",
      "releaseDate": "2026-08-07",
      "releaseLabel": "2026年8月7日(金)公開",
      "rating": "",
      "runtime": 91,
      "genre": "アニメ・ファミリー",
      "dubbed": true,
      "synopsis": "最強最悪のボスを求めて旅するミニオンズがたどり着いたのは夢あふれるハリウッド。自分たちでモンスター映画を作ろうとして本物のモンスターを召喚してしまい、街は大パニックに。",
      "posterUrl": "https://image.tmdb.org/t/p/w500/8wYHlLEIrEKvbfj83B11g7FKFd8.jpg",
      "tmdbId": 1315772,
      "mubichike": {
        "available": false,
        "salesLabel": "",
        "types": "",
        "price": "",
        "note": "公開中のため前売券の販売は終了しています",
        "url": ""
      },
      "bonuses": [],
      "bonusNote": "第2弾（オリジナルミニノート）までは配布終了。現時点で新たな特典が配布中かは確認できていません",
      "theaters": ["イオンシネマ みなとみらい"],
      "officialUrl": "",
      "note": "上映館が減ってきています（横浜ブルク13・T・ジョイ横浜の上映一覧には見当たりませんでした）",
      "needsCheck": false,
      "checkReason": ""
    },
    {
      "title": "映画クレヨンしんちゃん 奇々怪々！オラの妖怪バケ～ション",
      "audience": "kids",
      "status": "now",
      "releaseDate": "2026-07-31",
      "releaseLabel": "2026年7月31日(金)公開",
      "rating": "",
      "runtime": 101,
      "genre": "アニメ",
      "dubbed": false,
      "synopsis": "テレビアニメ「クレヨンしんちゃん」劇場版第33作。妖怪の国に迷い込んでしまった野原家が、どこか懐かしくも奇々怪々な世界で繰り広げる大冒険を描く。",
      "posterUrl": "https://image.tmdb.org/t/p/w500/15iwqqJVgFfeFh4Y1f8gg9yi2Fw.jpg",
      "tmdbId": 1598766,
      "mubichike": {
        "available": false,
        "salesLabel": "",
        "types": "",
        "price": "",
        "note": "公開中のため前売券の販売は終了しています",
        "url": ""
      },
      "bonuses": [],
      "bonusNote": "現時点では特典配布の有無を確認できていません",
      "theaters": ["横浜ブルク13", "イオンシネマ みなとみらい"],
      "officialUrl": "https://shin-ei-animation.jp/works/movie_shinchan_2026/",
      "note": "公開から約2か月経過していますが、横浜ブルク13・イオンシネマ みなとみらいで上映継続を確認しています",
      "needsCheck": false,
      "checkReason": ""
    },
    {
      "title": "スパイダーマン：ブランド・ニュー・デイ",
      "audience": "both",
      "status": "now",
      "releaseDate": "2026-07-31",
      "releaseLabel": "2026年7月31日(金)公開",
      "rating": "G",
      "runtime": 145,
      "genre": "洋画・アクション",
      "dubbed": true,
      "synopsis": "愛する人たちを守るため彼らの記憶から自らの存在を消したピーター・パーカーは、スパイダーマンとしてニューヨークの人々を守り続けている。そんな中、彼の体に驚くべき変異が起こり始める。",
      "posterUrl": "https://image.tmdb.org/t/p/w500/hvbs76wGMZYqJSvaRps5jDzHUhN.jpg",
      "tmdbId": 969681,
      "mubichike": {
        "available": false,
        "salesLabel": "",
        "types": "",
        "price": "",
        "note": "公開中のため前売券の販売は終了しています",
        "url": ""
      },
      "bonuses": [
        {
          "phase": "興収50億＆動員300万人突破記念",
          "period": "9/5(土)〜",
          "content": "オリジナルポストカード（A6サイズ）",
          "limited": true,
          "note": "数量限定、なくなり次第終了。配布開始から3週間以上経っているため、配布終了の劇場もあり得ます"
        }
      ],
      "bonusNote": "",
      "theaters": ["横浜ブルク13", "T・ジョイ横浜"],
      "officialUrl": "https://spiderman-movie.jp/",
      "note": "全米・国内ともにランキング上位。横浜ブルク13ではSCREENX上映も実施",
      "needsCheck": false,
      "checkReason": ""
    },
    {
      "title": "映画「宇宙なんちゃら こてつくん」うっかり出てきた宇宙人を探せ！",
      "audience": "kids",
      "status": "now",
      "releaseDate": "2026-09-11",
      "releaseLabel": "2026年9月11日(金)公開",
      "rating": "",
      "runtime": 50,
      "genre": "アニメ・ファミリー",
      "dubbed": false,
      "synopsis": "宇宙アカデミーのパイロット科1年生・こてつが、学園の仲間たちと一緒に宇宙人探しに乗り出す。テレビアニメの再編集映像とJAXAの実際の宇宙探査映像を組み合わせた作品。",
      "posterUrl": "",
      "tmdbId": null,
      "mubichike": {
        "available": false,
        "salesLabel": "",
        "types": "",
        "price": "",
        "note": "公開中のため前売券の販売は終了しています",
        "url": ""
      },
      "bonuses": [
        {
          "phase": "",
          "period": "9/11(金)〜",
          "content": "映画オリジナル『宇宙なんちゃらマシュマロシール』",
          "limited": true,
          "note": "先着順での配布です"
        }
      ],
      "bonusNote": "",
      "theaters": ["イオンシネマ みなとみらい"],
      "officialUrl": "https://space--academy.com/eiga.html",
      "note": "未就学児〜小学生向け。上映時間が短めの作品",
      "needsCheck": false,
      "checkReason": ""
    },
    {
      "title": "映画名探偵プリキュア！不思議な庭と2人の秘密",
      "audience": "kids",
      "status": "now",
      "releaseDate": "2026-09-18",
      "releaseLabel": "2026年9月18日(金)公開",
      "rating": "",
      "runtime": 73,
      "genre": "アニメ・ファミリー",
      "dubbed": false,
      "synopsis": "誕生日に妖精ポチタンと出会った明智あんなは、謎の光に飲み込まれてタイムスリップ。探偵志望の小林みくると出会い、名探偵プリキュアに変身して怪盗団ファントムに挑む、謎解きアドベンチャー。",
      "posterUrl": "https://image.tmdb.org/t/p/w500/bJg5Eh20xrIQIBgwCKJWLbajCsL.jpg",
      "tmdbId": 1663937,
      "mubichike": {
        "available": false,
        "salesLabel": "",
        "types": "",
        "price": "",
        "note": "公開中のため前売券の販売は終了しています",
        "url": ""
      },
      "bonuses": [
        {
          "phase": "第1弾",
          "period": "9/18(金)〜",
          "content": "ポチタンミラクルライト",
          "limited": true,
          "note": "配布対象は中学生以下のみ"
        },
        {
          "phase": "第2弾",
          "period": "9/25(金)〜10/1(木)",
          "content": "はなまる発見★チェンジングカード（「名探偵プリキュア!」「キミとアイドルプリキュア♪」「わんだふるぷりきゅあ!」の全3種からランダム1点、動かすと絵柄がチェンジ）",
          "limited": true,
          "note": "1週間限定・数量限定。第1弾と異なり大人も入手可能"
        }
      ],
      "bonusNote": "",
      "theaters": ["横浜ブルク13", "T・ジョイ横浜", "イオンシネマ みなとみらい"],
      "officialUrl": "https://www.precure-movie.com/",
      "note": "ミラクルライトは上映中に振って応援できる、こども向けの定番特典",
      "needsCheck": false,
      "checkReason": ""
    },
    {
      "title": "アベンジャーズ／エンドゲーム：アンコール",
      "audience": "both",
      "status": "now",
      "releaseDate": "2026-09-23",
      "releaseLabel": "2026年9月23日(水・祝)〜10月8日(木) 期間限定公開",
      "rating": "",
      "runtime": 186,
      "genre": "洋画・アクション",
      "dubbed": true,
      "synopsis": "サノスによって人類の半分が消滅した世界で、残されたアベンジャーズが最後の逆襲に挑む。12月公開の最新作『アベンジャーズ／ドゥームズデイ』への布石となる新規映像を追加した特別版。",
      "posterUrl": "https://image.tmdb.org/t/p/w500/uNWEDJzeH8VLHrs2iHkosYp2Y6W.jpg",
      "tmdbId": 299534,
      "mubichike": {
        "available": false,
        "salesLabel": "",
        "types": "",
        "price": "",
        "note": "期間限定の再上映のため、前売券の設定は確認できていません",
        "url": ""
      },
      "bonuses": [
        {
          "phase": "",
          "period": "9/23(水・祝)〜",
          "content": "特別ポスター（A3・リバーシブル仕様、『エンドゲーム：アンコール』と『ドゥームズデイ』のビジュアル）",
          "limited": true,
          "note": "一部劇場を除く。全フォーマット対象、劇場により数に限りあり"
        }
      ],
      "bonusNote": "",
      "theaters": ["横浜ブルク13", "T・ジョイ横浜", "イオンシネマ みなとみらい"],
      "officialUrl": "https://marvel.disney.co.jp/movie/avengers-doomsday/endgame-encore",
      "note": "10月8日(木)までの期間限定上映。横浜ブルク13・T・ジョイ横浜では字幕のプレミアムフォーマット上映あり",
      "needsCheck": false,
      "checkReason": ""
    },
    {
      "title": "トイ・ストーリー5",
      "audience": "both",
      "status": "now",
      "releaseDate": "2026-07-03",
      "releaseLabel": "2026年7月3日(金)公開",
      "rating": "G",
      "runtime": 102,
      "genre": "アニメ・ファミリー",
      "dubbed": true,
      "synopsis": "想像力豊かで内気な少女・ボニーの成長をそばで見守ってきたカウガール人形のジェシー。しかしタブレット端末「リリーパッド」の登場で日常は大きく変わり、ウッディやバズと共に新たなハイテクおもちゃたちとの騒動に巻き込まれていく。",
      "posterUrl": "https://image.tmdb.org/t/p/w500/dEoN5k2ulqk9mhEwVrapciKJm8s.jpg",
      "tmdbId": 1084244,
      "mubichike": {
        "available": false,
        "salesLabel": "",
        "types": "",
        "price": "",
        "note": "公開中のため前売券の販売は終了しています",
        "url": ""
      },
      "bonuses": [
        {
          "phase": "トイ・ストーリー30周年記念",
          "period": "9/12(金)〜",
          "content": "30周年記念ビジュアル＆『トイ・ストーリー5』特別ビジュアル ポストカードセット",
          "limited": true,
          "note": "一部劇場を除く、なくなり次第配布終了"
        }
      ],
      "bonusNote": "",
      "theaters": ["横浜ブルク13", "T・ジョイ横浜", "イオンシネマ みなとみらい"],
      "officialUrl": "https://www.disney.co.jp/movie/toy5",
      "note": "公開から約3か月経過していますが、横浜周辺でも吹替版の上映継続を確認しています",
      "needsCheck": false,
      "checkReason": ""
    },
    {
      "title": "劇場版ダーウィンが来た！世界のネコのなかまたち",
      "audience": "both",
      "status": "soon",
      "releaseDate": "2026-10-02",
      "releaseLabel": "2026年10月2日(金)公開",
      "rating": "",
      "runtime": 80,
      "genre": "ドキュメンタリー",
      "dubbed": false,
      "synopsis": "NHKの人気自然番組の劇場版。ライオンやチーターの狩り、マヌルネコ独特の狩りの手法など、世界の40種類以上のネコ科動物の生態と習性を大スクリーンで紹介するネイチャー・ドキュメンタリー。ナレーションは水瀬いのり。",
      "posterUrl": "",
      "tmdbId": null,
      "mubichike": {
        "available": true,
        "salesLabel": "〜2026年10月1日(木)23:59（公開前日まで）",
        "types": "ムビチケ前売券（オンライン）",
        "price": "一般1,500円 / 小人900円",
        "note": "購入者限定の鑑賞特典としてムビチケデジタルカードあり",
        "url": "https://ticket.moviewalker.jp/film/093341"
      },
      "bonuses": [],
      "bonusNote": "入場者特典は現時点では確認できていません",
      "theaters": [],
      "officialUrl": "https://www.worldcat-darwin.com/",
      "note": "アニメ以外でこどもと楽しめる動物ドキュメンタリー",
      "needsCheck": false,
      "checkReason": ""
    },
    {
      "title": "映画 ひつじのショーン かぼちゃ畑の怪物！",
      "audience": "both",
      "status": "soon",
      "releaseDate": "2026-10-23",
      "releaseLabel": "2026年10月23日(金)公開",
      "rating": "",
      "runtime": 81,
      "genre": "アニメ・ファミリー",
      "dubbed": true,
      "synopsis": "ハロウィンの準備でにぎわう牧場で、牧場主が大切なかぼちゃ畑をめちゃくちゃにしてしまう。ショーンは謎の薬で問題を解決しようとするが、牧場主は行方不明になり、もじゃもじゃの怪物まで現れて大騒動に。アードマン・アニメーションズ50周年記念作品。",
      "posterUrl": "https://image.tmdb.org/t/p/w500/mMOptSPBVGUA9GHgnpsC35GzZ7e.jpg",
      "tmdbId": 1477104,
      "mubichike": {
        "available": true,
        "salesLabel": "〜2026年10月22日(木)23:59（公開前日まで）",
        "types": "前売オンライン券 / 前売カード券（キーチェーン付・ポーチ付もあり）",
        "price": "一般1,600円 / 小人900円（キーチェーン付カード券2,900円、ポーチ付カード券3,100円）",
        "note": "購入特典としてオリジナルスマホ壁紙（2種）あり",
        "url": "https://ticket.moviewalker.jp/film/093461"
      },
      "bonuses": [],
      "bonusNote": "入場者特典は現時点では発表されていません",
      "theaters": [],
      "officialUrl": "https://movies.shochiku.co.jp/shaun-kabocha/",
      "note": "セリフがほとんど無いクレイアニメなので、小さなこどもでも楽しみやすいシリーズ。日本語版には中村倫也さん・ガンバレルーヤが参加",
      "needsCheck": false,
      "checkReason": ""
    },
    {
      "title": "白鳥とコウモリ",
      "audience": "adult",
      "status": "now",
      "releaseDate": "2026-09-04",
      "releaseLabel": "2026年9月4日(金)公開",
      "rating": "G",
      "runtime": 145,
      "genre": "邦画・ミステリー",
      "dubbed": false,
      "synopsis": "善良な弁護士が刺殺された事件は、容疑者の自供により解決したはずだった。しかし容疑者の息子と被害者の娘は事件に違和感を抱き、出会うはずのない2人が真実を追い始める。東野圭吾原作。",
      "posterUrl": "https://image.tmdb.org/t/p/w500/jIEyBR9gCrDMEQ7UcxWmJVj2zDi.jpg",
      "tmdbId": 1621964,
      "mubichike": {
        "available": false,
        "salesLabel": "",
        "types": "",
        "price": "",
        "note": "公開中のため前売券の販売は終了しています",
        "url": ""
      },
      "bonuses": [],
      "bonusNote": "入場者特典は確認できていません（劇場グッズ・パンフレットの販売あり）",
      "theaters": ["横浜ブルク13", "T・ジョイ横浜", "イオンシネマ みなとみらい"],
      "officialUrl": "https://movies.shochiku.co.jp/eiga-hakuchotokomori/",
      "note": "国内ランキング上位",
      "needsCheck": false,
      "checkReason": ""
    },
    {
      "title": "バックルームズ",
      "audience": "adult",
      "status": "now",
      "releaseDate": "2026-09-04",
      "releaseLabel": "2026年9月4日(金)公開",
      "rating": "G",
      "runtime": 127,
      "genre": "洋画・ホラー",
      "dubbed": true,
      "synopsis": "家具店を経営するクラークは、店の地下から現実には存在しない奇妙な空間へ迷い込む。黄色い壁紙と蛍光灯に照らされた終わりのない部屋と廊下が続く不可思議な世界の謎に挑む、都市伝説発の恐怖体験。",
      "posterUrl": "https://image.tmdb.org/t/p/w500/z52Eabu4xm5I8ksqdKOSylo5wWL.jpg",
      "tmdbId": 1083381,
      "mubichike": {
        "available": false,
        "salesLabel": "",
        "types": "",
        "price": "",
        "note": "公開中のため前売券の販売は終了しています",
        "url": ""
      },
      "bonuses": [
        {
          "phase": "第3弾",
          "period": "9/18(金)〜",
          "content": "『バックルームズ』黄色い防護服ステッカー",
          "limited": true,
          "note": "一部劇場を除く、先着数量限定、なくなり次第終了"
        }
      ],
      "bonusNote": "",
      "theaters": ["横浜ブルク13", "T・ジョイ横浜", "イオンシネマ みなとみらい"],
      "officialUrl": "https://a24jp.com/films/backrooms/",
      "note": "全米初登場1位、世界44か国で初登場1位を記録したA24配給のヒットホラー",
      "needsCheck": false,
      "checkReason": ""
    },
    {
      "title": "劇場版 魔法少女まどか☆マギカ ワルプルギスの廻天",
      "audience": "adult",
      "status": "now",
      "releaseDate": "2026-08-28",
      "releaseLabel": "2026年8月28日(金)公開",
      "rating": "G",
      "runtime": 119,
      "genre": "アニメ",
      "dubbed": false,
      "synopsis": "『叛逆の物語』の事件を経て、世界は表向き均衡を取り戻したかに見えた。しかしその平和はあまりにも脆く、ワルプルギスの夜に関連する新たな脅威が現れる。",
      "posterUrl": "https://image.tmdb.org/t/p/w500/tc7wW6whJSvxM9f5RdqmQVpdl6n.jpg",
      "tmdbId": 822653,
      "mubichike": {
        "available": false,
        "salesLabel": "",
        "types": "",
        "price": "",
        "note": "公開中のため前売券の販売は終了しています",
        "url": ""
      },
      "bonuses": [
        {
          "phase": "第5週目",
          "period": "9/26(土)〜10/2(金)",
          "content": "シャフト描きおろしポストカード",
          "limited": true,
          "note": "なくなり次第配布終了"
        }
      ],
      "bonusNote": "",
      "theaters": ["横浜ブルク13", "T・ジョイ横浜", "イオンシネマ みなとみらい"],
      "officialUrl": "https://www.madoka-magica.com/wr/",
      "note": "アニメだが内容は大人向け。小学生以下には不向き",
      "needsCheck": false,
      "checkReason": ""
    },
    {
      "title": "オデュッセイア",
      "audience": "adult",
      "status": "now",
      "releaseDate": "2026-09-11",
      "releaseLabel": "2026年9月11日(金)公開",
      "rating": "",
      "runtime": 172,
      "genre": "洋画・ドラマ",
      "dubbed": false,
      "synopsis": "トロイア戦争の終結後、イタケーの伝説的な王オデュッセウスは、故郷への長く危険に満ちた帰還の旅に出る。神々の気まぐれや神話の怪物たちが、彼の知略と人間性を試す。クリストファー・ノーラン監督最新作。",
      "posterUrl": "https://image.tmdb.org/t/p/w500/oe40oI7aulGLkoNDEZWxyeIQGZq.jpg",
      "tmdbId": 1368337,
      "mubichike": {
        "available": false,
        "salesLabel": "",
        "types": "",
        "price": "",
        "note": "公開中のため前売券の販売は終了しています",
        "url": ""
      },
      "bonuses": [],
      "bonusNote": "入場者特典は現時点では確認できていません",
      "theaters": ["横浜ブルク13", "T・ジョイ横浜", "イオンシネマ みなとみらい"],
      "officialUrl": "https://odyssey-film.jp/",
      "note": "全米ランキング上位。T・ジョイ横浜ではDolby Cinema上映あり",
      "needsCheck": false,
      "checkReason": ""
    },
    {
      "title": "最終楽章 響け！ユーフォニアム 後編",
      "audience": "adult",
      "status": "now",
      "releaseDate": "2026-09-11",
      "releaseLabel": "2026年9月11日(金)公開",
      "rating": "",
      "runtime": 128,
      "genre": "アニメ",
      "dubbed": false,
      "synopsis": "難関の関西大会を突破し、全国大会出場に沸き立つ北宇治高校吹奏楽部。全国大会出場をかけたオーディションに向け、部員たちの葛藤と決意を描くシリーズ最終章の後編。",
      "posterUrl": "https://image.tmdb.org/t/p/w500/3nVufzgnnT9it02P7fa6KAxyKLu.jpg",
      "tmdbId": 1494419,
      "mubichike": {
        "available": false,
        "salesLabel": "",
        "types": "",
        "price": "",
        "note": "公開中のため前売券の販売は終了しています",
        "url": ""
      },
      "bonuses": [
        {
          "phase": "3週目",
          "period": "9/25(金)〜10/1(木)",
          "content": "オーディオドラマダウンロードカード（全2種）",
          "limited": true,
          "note": "なくなり次第配布終了"
        }
      ],
      "bonusNote": "",
      "theaters": ["横浜ブルク13", "T・ジョイ横浜", "イオンシネマ みなとみらい"],
      "officialUrl": "https://anime-eupho.com/",
      "note": "前編を観ていることが前提のシリーズ作品。横浜ブルク13では日本語字幕付き上映あり",
      "needsCheck": false,
      "checkReason": ""
    },
    {
      "title": "踊る大捜査線 N.E.W. メトロポリスを駆け抜けろ！",
      "audience": "adult",
      "status": "now",
      "releaseDate": "2026-09-18",
      "releaseLabel": "2026年9月18日(金)公開",
      "rating": "G",
      "runtime": 141,
      "genre": "邦画・アクション",
      "dubbed": false,
      "synopsis": "東京都内で誘拐事件が発生。犯人は身代金を指定場所まで持ってくるよう指示し、間に合わなければ街を爆破すると予告する。3Dプリンター拳銃による連続殺人事件も発生する中、青島は仲間と事件解決に奔走する。",
      "posterUrl": "https://image.tmdb.org/t/p/w500/zxpus1lIDG7wqAuzsD0zgM6mXwM.jpg",
      "tmdbId": 1491083,
      "mubichike": {
        "available": false,
        "salesLabel": "",
        "types": "",
        "price": "",
        "note": "公開中のため前売券の販売は終了しています",
        "url": ""
      },
      "bonuses": [
        {
          "phase": "",
          "period": "9/18(金)〜",
          "content": "特別捜査本部資料",
          "limited": true,
          "note": "先着順、なくなり次第配布終了"
        }
      ],
      "bonusNote": "",
      "theaters": ["横浜ブルク13", "T・ジョイ横浜", "イオンシネマ みなとみらい"],
      "officialUrl": "https://odoru.com/odorunew/tickets.html",
      "note": "主題歌は織田裕二「Love Somebody」",
      "needsCheck": false,
      "checkReason": ""
    },
    {
      "title": "八つ墓村",
      "audience": "adult",
      "status": "now",
      "releaseDate": "2026-09-18",
      "releaseLabel": "2026年9月18日(金)公開",
      "rating": "G",
      "runtime": 117,
      "genre": "邦画・ミステリー",
      "dubbed": false,
      "synopsis": "大学生・井川辰弥のもとに舞い込んだ母の訃報。奇妙な探偵・金田一耕助に誘われ、岡山県山奥に潜む「八つ墓村」を訪れる。清水崇監督×尾上松也主演による横溝正史原作の完全新作映画化。",
      "posterUrl": "https://image.tmdb.org/t/p/w500/3xLSVAQZAs1DEUNm1TKYzx0kiLT.jpg",
      "tmdbId": 1716622,
      "mubichike": {
        "available": false,
        "salesLabel": "",
        "types": "",
        "price": "",
        "note": "公開中のため前売券の販売は終了しています",
        "url": ""
      },
      "bonuses": [
        {
          "phase": "",
          "period": "9/18(金)〜",
          "content": "八つ墓村オリジナルたたりカード（裏面に鑑賞者向けの秘密のメッセージと二次元コード付き）",
          "limited": true,
          "note": "なくなり次第配布終了。TOHOシネマズでは配布なし"
        }
      ],
      "bonusNote": "",
      "theaters": ["横浜ブルク13", "T・ジョイ横浜", "イオンシネマ みなとみらい"],
      "officialUrl": "https://movies.shochiku.co.jp/yatsuhakamura-movie/",
      "note": "清水崇監督×尾上松也の新解釈による『八つ墓村』",
      "needsCheck": false,
      "checkReason": ""
    },
    {
      "title": "ルックバック",
      "audience": "adult",
      "status": "now",
      "releaseDate": "2026-09-11",
      "releaseLabel": "2026年9月11日(金)公開",
      "rating": "G",
      "runtime": 99,
      "genre": "邦画・ドラマ",
      "dubbed": false,
      "synopsis": "学級新聞に4コマ漫画を連載する小学4年生の藤野は、不登校の同級生・京本の圧倒的な画力に出会い衝撃を受ける。二人はやがて漫画家を志し、ライバルであり創作の仲間として歩みを共にしていく。藤本タツキ原作、是枝裕和監督による実写映画化。",
      "posterUrl": "https://image.tmdb.org/t/p/w500/6eXDHPwPDTZTgf4wuGIP49bxxJV.jpg",
      "tmdbId": 1591675,
      "mubichike": {
        "available": false,
        "salesLabel": "",
        "types": "",
        "price": "",
        "note": "公開中のため前売券の販売は終了しています",
        "url": ""
      },
      "bonuses": [
        {
          "phase": "第2弾",
          "period": "9/18(金)〜",
          "content": "全64ページの特別小冊子「Special Booklet Volume1」（劇中作「メタルパレード」完成版41ページ、藤本タツキ×是枝裕和ら対談を収録）",
          "limited": true,
          "note": "なくなり次第配布終了"
        }
      ],
      "bonusNote": "",
      "theaters": ["横浜ブルク13", "T・ジョイ横浜", "イオンシネマ みなとみらい"],
      "officialUrl": "https://k2pic.com/film/lb/",
      "note": "第83回ヴェネチア国際映画祭コンペティション部門に正式出品",
      "needsCheck": false,
      "checkReason": ""
    },
    {
      "title": "新劇場版 銀魂 -吉原大炎上-＜超炎上版＞",
      "audience": "adult",
      "status": "now",
      "releaseDate": "2026-09-25",
      "releaseLabel": "2026年9月25日(金)公開（＜超炎上版＞として再上映）",
      "rating": "",
      "runtime": 124,
      "genre": "アニメ",
      "dubbed": false,
      "synopsis": "2026年2月に公開された『新劇場版 銀魂 -吉原大炎上-』の＜超炎上版＞。地下遊郭・吉原を舞台に、坂田銀時ら万事屋が、夜兎族の鳳仙が支配する街で囚われた人々を救うため激しい戦いに挑む。",
      "posterUrl": "https://image.tmdb.org/t/p/w500/5F7YrauGDP2tbzz84KKwji2MB3e.jpg",
      "tmdbId": 1530941,
      "mubichike": {
        "available": false,
        "salesLabel": "",
        "types": "",
        "price": "",
        "note": "公開中のため前売券の販売は終了しています",
        "url": ""
      },
      "bonuses": [
        {
          "phase": "第1弾",
          "period": "9/25(金)〜10/1(木)",
          "content": "「銀さんもうすぐお誕生日おめでとう色紙」全4種",
          "limited": true,
          "note": "劇場により数に限りあり、無くなり次第終了"
        },
        {
          "phase": "第2弾",
          "period": "10/2(金)〜10/8(木)",
          "content": "「つながるバトルイラストカード＜万事屋＞」",
          "limited": true,
          "note": "劇場により数に限りあり、無くなり次第終了"
        },
        {
          "phase": "第3弾",
          "period": "10/9(金)〜10/15(木)",
          "content": "「つながるバトルイラストカード＜吉原桃源郷・夜兎＞」（第2弾とつなげると1枚のバトルイラストに）",
          "limited": true,
          "note": "劇場により数に限りあり、無くなり次第終了"
        }
      ],
      "bonusNote": "",
      "theaters": ["横浜ブルク13", "T・ジョイ横浜", "イオンシネマ みなとみらい"],
      "officialUrl": "https://www.anime-gintama.com/movie2026/",
      "note": "週替わりで特典が変わるため、欲しい特典がある場合は配布期間に注意",
      "needsCheck": false,
      "checkReason": ""
    },
    {
      "title": "マッチング TRUE LOVE",
      "audience": "adult",
      "status": "now",
      "releaseDate": "2026-09-25",
      "releaseLabel": "2026年9月25日(金)公開",
      "rating": "PG12",
      "runtime": 107,
      "genre": "邦画・サスペンス",
      "dubbed": false,
      "synopsis": "マッチングアプリによる連続殺人事件から2年。恋人の吐夢が失踪し、模倣殺人まで起きる中、輪花は南の島のリゾートで開かれるマッチングツアーに参加し、「真実の愛を証明できなければ殺される」デスゲームに巻き込まれる。土屋太鳳×佐久間大介、内田英治監督。",
      "posterUrl": "https://image.tmdb.org/t/p/w500/kWIqWDagKVlCXxwHzxsmDPJU2ld.jpg",
      "tmdbId": 1595400,
      "mubichike": {
        "available": false,
        "salesLabel": "",
        "types": "",
        "price": "",
        "note": "公開中のため前売券の販売は終了しています",
        "url": ""
      },
      "bonuses": [],
      "bonusNote": "入場者特典は現時点では確認できていません",
      "theaters": ["横浜ブルク13", "T・ジョイ横浜", "イオンシネマ みなとみらい"],
      "officialUrl": "https://movies.kadokawa.co.jp/matching/",
      "note": "2024年のヒット作『マッチング』の続編",
      "needsCheck": false,
      "checkReason": ""
    },
    {
      "title": "汝、星のごとく",
      "audience": "adult",
      "status": "soon",
      "releaseDate": "2026-10-09",
      "releaseLabel": "2026年10月9日(金)公開",
      "rating": "PG12",
      "runtime": 135,
      "genre": "邦画・ドラマ",
      "dubbed": false,
      "synopsis": "瀬戸内のとある島で高校時代に出会った、漫画家を夢見る青埜櫂と刺繍の仕事を志す井上暁海。本屋大賞受賞のベストセラー小説を原作に、15年にわたる2人の切ない愛と選択を描く。横浜流星×広瀬すずW主演。",
      "posterUrl": "https://image.tmdb.org/t/p/w500/nRoVOvMPOEM9GuHu5FKGigbXzVT.jpg",
      "tmdbId": 1590933,
      "mubichike": {
        "available": true,
        "salesLabel": "〜2026年10月8日(木)23:59（公開前日まで）",
        "types": "ムビチケカード / 前売オンライン券",
        "price": "1,500円（税込）",
        "note": "購入者限定の鑑賞特典（ムビチケデジタルカード）は準備中と案内されています",
        "url": "https://ticket.moviewalker.jp/film/090318"
      },
      "bonuses": [],
      "bonusNote": "入場者特典は現時点では確認できていません",
      "theaters": ["横浜ブルク13", "T・ジョイ横浜", "イオンシネマ みなとみらい"],
      "officialUrl": "https://nanji.toho-movie.jp/",
      "note": "本屋大賞受賞作の実写映画化。藤井道人監督",
      "needsCheck": false,
      "checkReason": ""
    },
    {
      "title": "バイオハザード",
      "audience": "adult",
      "status": "soon",
      "releaseDate": "2026-10-09",
      "releaseLabel": "2026年10月9日(金)公開",
      "rating": "",
      "runtime": 90,
      "genre": "洋画・ホラー",
      "dubbed": true,
      "synopsis": "主人公は、どこにでもいる普通の配達員ブライアン。ある医薬品をラクーン・シティに届ける仕事を受けたことから、命運を懸けた地獄の一夜が始まる。『WEAPONS／ウェポンズ』のザック・クレッガー監督がゲームを完全新作として再構築したサバイバルホラー。",
      "posterUrl": "https://image.tmdb.org/t/p/w500/wHXSnGH3zQtvpxPwaBXMoS9o8Vl.jpg",
      "tmdbId": 1423191,
      "mubichike": {
        "available": true,
        "salesLabel": "〜2026年10月8日(木)23:59（公開前日まで）",
        "types": "前売オンライン券",
        "price": "一般1,700円",
        "note": "購入者限定の鑑賞特典としてムビチケデジタルカードあり",
        "url": "https://ticket.moviewalker.jp/film/093315"
      },
      "bonuses": [],
      "bonusNote": "入場者特典は現時点では発表されていません",
      "theaters": [],
      "officialUrl": "https://biomovie.jp/",
      "note": "日本語吹替版あり（下野紘、早見沙織ほか）",
      "needsCheck": false,
      "checkReason": ""
    }
  ]
}
;
